version: '3.8'

services:
  devops-agent:
    build: .
    container_name: devops-agent-live
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - IA_MODE=${IA_MODE}
      - GROQ_KEY=${GROQ_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}